name: Playwright CI

on:
  push:
    branches:
      - main       # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main       # Trigger on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (use the appropriate version of Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Install Playwright browsers
      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps

      # Step 5: Run Playwright tests
      - name: Run Playwright tests
        run: |
          npx playwright test

      # Step 6: Upload screenshots, videos, and reports as artifacts
      - name: Upload screenshots and videos
        uses: actions/upload-artifact@v2
        with:
          name: playwright-artifacts
          path: |
            test-reports
            **/*.png
            **/*.mp4

